'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase';
import { useRouter } from 'next/navigation';

type App={id:string;full_name:string;email:string;phone:string|null;state:string|null;education:string|null;experience:string|null;requested_track:string|null;motivation:string|null;status:string;created_at:string};

export default function Admin(){
 const router=useRouter(); const [apps,setApps]=useState<App[]>([]); const [tracks,setTracks]=useState<any[]>([]);
 const [selected,setSelected]=useState<App|null>(null); const [error,setError]=useState(''); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(true);
 const [form,setForm]=useState({title:'',slug:'',description:'',track_id:'',level:'beginner'});
 async function load(){setLoading(true);const r=await fetch('/api/applications');const d=await r.json();if(!r.ok)setError(d.error||'Unauthorized');else setApps(d.applications||[]);setLoading(false);}
 useEffect(()=>{createClient().from('skill_tracks').select('id,name').order('sort_order').then(({data})=>setTracks(data||[]));load();},[]);
 async function review(id:string,status:string){const note=window.prompt(status==='rejected'?'Optional rejection note:':'Optional review note:')||'';const r=await fetch('/api/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status,review_note:note})});const d=await r.json();if(!r.ok)return setError(d.error||'Action failed');setMsg(status==='approved'?(d.invitationSent?'Approved and invitation sent.':'Approved. Email was already registered.'):'Application updated.');setSelected(null);load();}
 async function course(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/courses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setMsg(r.ok?'Course created as draft.':d.error);}
 const pending=apps.filter(a=>a.status==='pending'||a.status==='more_information').length;
 return <main className="min-h-screen grid-bg"><div className="mx-auto max-w-7xl px-5 py-10">
  <button onClick={()=>router.push('/dashboard')} className="text-slate-400">← Dashboard</button>
  <p className="mt-5 text-xs uppercase tracking-widest text-blue-400">Company Administration</p><h1 className="mt-2 text-3xl font-black">FlashDev Academy Admin</h1>
  {error&&<div className="mt-5 rounded-xl border border-red-500/20 p-4 text-sm text-red-300">{error}</div>}{msg&&<div className="mt-5 rounded-xl border border-emerald-500/20 p-4 text-sm text-emerald-300">{msg}</div>}
  <div className="mt-8 grid gap-4 md:grid-cols-3"><div className="glass rounded-2xl p-5"><p className="text-slate-500">Pending</p><b className="text-3xl">{pending}</b></div><div className="glass rounded-2xl p-5"><p className="text-slate-500">Approved</p><b className="text-3xl">{apps.filter(a=>a.status==='approved').length}</b></div><div className="glass rounded-2xl p-5"><p className="text-slate-500">Total</p><b className="text-3xl">{apps.length}</b></div></div>
  <section className="glass mt-8 rounded-2xl p-6"><div className="flex justify-between"><div><p className="text-xs uppercase text-blue-400">Admissions</p><h2 className="text-2xl font-black">Applications</h2></div><button onClick={load} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Refresh</button></div>
   <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-3">Applicant</th><th className="p-3">Track</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>
   {apps.map(a=><tr key={a.id} className="border-b border-white/5"><td className="p-3"><b>{a.full_name}</b><div className="text-xs text-slate-500">{a.email}</div></td><td className="p-3">{a.requested_track||'—'}</td><td className="p-3 capitalize">{a.status.replace('_',' ')}</td><td className="p-3"><button onClick={()=>setSelected(a)} className="rounded-lg border border-white/10 px-3 py-2">Review</button></td></tr>)}
   {!apps.length&&!loading&&<tr><td colSpan={4} className="p-8 text-center text-slate-500">No applications yet.</td></tr>}</tbody></table></div>
  </section>
  {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-5"><div className="mx-auto mt-10 max-w-2xl glass rounded-2xl p-7"><div className="flex justify-between"><div><p className="text-xs uppercase text-blue-400">Applicant review</p><h2 className="text-2xl font-black">{selected.full_name}</h2></div><button onClick={()=>setSelected(null)}>✕</button></div><div className="mt-6 space-y-4 text-sm"><p><b>Email:</b> {selected.email}</p><p><b>Phone:</b> {selected.phone||'—'}</p><p><b>State:</b> {selected.state||'—'}</p><p><b>Education:</b> {selected.education||'—'}</p><p><b>Track:</b> {selected.requested_track||'—'}</p><p><b>Experience:</b><br/>{selected.experience||'—'}</p><p><b>Motivation:</b><br/>{selected.motivation||'—'}</p></div>{(selected.status==='pending'||selected.status==='more_information')&&<div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>review(selected.id,'approved')} className="btn btn-primary">Approve & invite</button><button onClick={()=>review(selected.id,'more_information')} className="rounded-lg border border-white/10 px-4 py-2">Request information</button><button onClick={()=>review(selected.id,'rejected')} className="rounded-lg border border-red-500/20 px-4 py-2 text-red-300">Reject</button></div>}</div></div>}
  <section className="glass mt-8 rounded-2xl p-6"><p className="text-xs uppercase text-blue-400">Course management</p><h2 className="text-2xl font-black">Create course</h2><form onSubmit={course} className="mt-5 grid gap-4 md:grid-cols-2"><input className="input" placeholder="Course title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><input className="input" placeholder="slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} required/><textarea className="input md:col-span-2" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select className="input" value={form.track_id} onChange={e=>setForm({...form,track_id:e.target.value})} required><option value="">Select skill track</option>{tracks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className="input" value={form.level} onChange={e=>setForm({...form,level:e.target.value})}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select><button className="btn btn-primary md:col-span-2">Create draft course</button></form></section>
 </div></main>;
}
