create extension if not exists pgcrypto;
do $$begin create type public.user_role as enum('student','instructor','admin');exception when duplicate_object then null;end$$;
do $$begin create type public.course_level as enum('beginner','intermediate','advanced');exception when duplicate_object then null;end$$;
do $$begin create type public.lesson_stage as enum('video','notes','practice','quiz','mastery','completed');exception when duplicate_object then null;end$$;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,student_id text unique,role public.user_role not null default 'student',avatar_url text,bio text,xp integer not null default 0,streak_days integer not null default 0,last_active_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.skill_tracks(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text,icon text,color text,published boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.courses(id uuid primary key default gen_random_uuid(),track_id uuid not null references public.skill_tracks(id) on delete cascade,title text not null,slug text unique not null,description text,level public.course_level not null default 'beginner',thumbnail_url text,published boolean not null default false,created_by uuid references public.profiles(id) on delete set null,estimated_hours numeric(6,2),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.modules(id uuid primary key default gen_random_uuid(),course_id uuid not null references public.courses(id) on delete cascade,title text not null,description text,sort_order integer not null default 0,created_at timestamptz not null default now(),unique(course_id,sort_order));
create table if not exists public.lessons(id uuid primary key default gen_random_uuid(),module_id uuid not null references public.modules(id) on delete cascade,title text not null,slug text not null,description text,video_url text,video_provider text,transcript text,notes_markdown text,resources jsonb not null default '[]'::jsonb,coding_language text,starter_code text,mastery_score integer not null default 100 check(mastery_score between 0 and 100),sort_order integer not null default 0,published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(module_id,slug));
create table if not exists public.coding_exercises(id uuid primary key default gen_random_uuid(),lesson_id uuid not null references public.lessons(id) on delete cascade,title text not null,instructions text not null,language text not null,starter_code text,solution_hint text,test_command text,timeout_ms integer not null default 5000,sort_order integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.exercise_test_cases(id uuid primary key default gen_random_uuid(),exercise_id uuid not null references public.coding_exercises(id) on delete cascade,name text not null,input_data jsonb not null default '{}'::jsonb,expected_output text,points integer not null default 1,hidden boolean not null default false,sort_order integer not null default 0);
create table if not exists public.enrollments(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,enrolled_at timestamptz not null default now(),completed_at timestamptz,unique(user_id,course_id));
create table if not exists public.lesson_progress(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,lesson_id uuid not null references public.lessons(id) on delete cascade,current_stage public.lesson_stage not null default 'video',video_completed boolean not null default false,notes_completed boolean not null default false,practice_completed boolean not null default false,quiz_completed boolean not null default false,mastery_score integer not null default 0,code_runs integer not null default 0,passed_tests integer not null default 0,total_tests integer not null default 0,completed_at timestamptz,updated_at timestamptz not null default now(),unique(user_id,lesson_id));
create table if not exists public.notes(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,lesson_id uuid not null references public.lessons(id) on delete cascade,title text,content text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,lesson_id));
create table if not exists public.quizzes(id uuid primary key default gen_random_uuid(),lesson_id uuid not null references public.lessons(id) on delete cascade,title text not null,passing_score integer not null default 100);
create table if not exists public.quiz_questions(id uuid primary key default gen_random_uuid(),quiz_id uuid not null references public.quizzes(id) on delete cascade,question text not null,question_type text not null default 'mcq',sort_order integer not null default 0);
create table if not exists public.quiz_options(id uuid primary key default gen_random_uuid(),question_id uuid not null references public.quiz_questions(id) on delete cascade,option_text text not null,is_correct boolean not null default false,sort_order integer not null default 0);
create table if not exists public.quiz_attempts(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,quiz_id uuid not null references public.quizzes(id) on delete cascade,score integer not null default 0,answers jsonb not null default '{}',passed boolean not null default false,attempted_at timestamptz not null default now());
create table if not exists public.certificates(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,verification_id text unique not null,issued_at timestamptz not null default now(),unique(user_id,course_id));
create table if not exists public.discussions(id uuid primary key default gen_random_uuid(),lesson_id uuid not null references public.lessons(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,body text not null,created_at timestamptz not null default now());
create index if not exists courses_track_idx on public.courses(track_id);create index if not exists modules_course_idx on public.modules(course_id);create index if not exists lessons_module_idx on public.lessons(module_id);create index if not exists progress_user_idx on public.lesson_progress(user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,student_id) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email),'FD-'||upper(substr(replace(new.id::text,'-',''),1,8))) on conflict(id) do nothing;return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
alter table public.profiles enable row level security;alter table public.skill_tracks enable row level security;alter table public.courses enable row level security;alter table public.modules enable row level security;alter table public.lessons enable row level security;alter table public.coding_exercises enable row level security;alter table public.exercise_test_cases enable row level security;alter table public.enrollments enable row level security;alter table public.lesson_progress enable row level security;alter table public.notes enable row level security;alter table public.quizzes enable row level security;alter table public.quiz_questions enable row level security;alter table public.quiz_options enable row level security;alter table public.quiz_attempts enable row level security;alter table public.certificates enable row level security;alter table public.discussions enable row level security;
create policy if not exists "profile_self" on public.profiles for select to authenticated using(id=auth.uid());
create policy if not exists "profile_update_self" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy if not exists "tracks_public" on public.skill_tracks for select to anon,authenticated using(published=true);
create policy if not exists "courses_public" on public.courses for select to anon,authenticated using(published=true);
create policy if not exists "modules_public" on public.modules for select to anon,authenticated using(exists(select 1 from public.courses c where c.id=course_id and c.published=true));
create policy if not exists "lessons_public" on public.lessons for select to anon,authenticated using(exists(select 1 from public.modules m join public.courses c on c.id=m.course_id where m.id=module_id and c.published=true and public.lessons.published=true));
create policy if not exists "enrollments_self" on public.enrollments for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy if not exists "progress_self" on public.lesson_progress for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy if not exists "notes_self" on public.notes for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy if not exists "quiz_attempts_self" on public.quiz_attempts for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy if not exists "certificates_self" on public.certificates for select to authenticated using(user_id=auth.uid());
create policy if not exists "discussions_auth" on public.discussions for select to authenticated using(true);
create policy if not exists "discussions_insert" on public.discussions for insert to authenticated with check(user_id=auth.uid());
insert into public.skill_tracks(slug,name,description,icon,sort_order) values
('web-development','Web Development','Frontend, backend, APIs and full-stack application development.','globe',1),
('python-programming','Python Programming','Python fundamentals, automation and application development.','code',2),
('data-analysis','Data Analysis','Data cleaning, analysis, visualization and reporting.','chart',3),
('artificial-intelligence-machine-learning','AI & Machine Learning','Practical AI and machine learning foundations.','brain',4),
('cybersecurity','Cybersecurity','Security fundamentals and defensive practice.','shield',5),
('cloud-devops','Cloud Computing & DevOps','Cloud infrastructure, containers, deployment and CI/CD.','cloud',6),
('mobile-development','Mobile App Development','Build practical mobile applications.','smartphone',7),
('ui-ux-design','UI/UX Design','Research, interface design and prototyping.','pen-tool',8),
('blockchain-web3','Blockchain & Web3','Blockchain concepts and decentralized applications.','blocks',9),
('database-sql','Database & SQL','SQL, data modeling and database engineering.','database',10),
('software-testing-qa','Software Testing & QA','Testing, automation and quality assurance.','check',11),
('programming-fundamentals','Programming Fundamentals','Algorithms, data structures and problem solving.','terminal',12),
('digital-productivity','Digital Productivity','Practical digital literacy and workplace technology.','sparkles',13),
('digital-marketing','Digital Marketing','Digital campaigns, content and analytics.','megaphone',14)
on conflict(slug) do nothing;